name: Python application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make pw-dependencies   
    - name: Run application
      run: |
        make run &
    - name: Run application
      run: |
        sleep 3
    - name: Run e2e
      run: |
        make test-e2e 
